
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTAND LPAREN NOT OR RPAREN VARIABLEexpression : VARIABLEexpression : NOT expression %prec NOTexpression : LPAREN expression RPARENexpression : expression AND expressionexpression : expression OR expression'
    
_lr_action_items = {'VARIABLE':([0,3,4,5,6,],[2,2,2,2,2,]),'NOT':([0,3,4,5,6,],[3,3,3,3,3,]),'LPAREN':([0,3,4,5,6,],[4,4,4,4,4,]),'$end':([1,2,7,9,10,11,],[0,-1,-2,-4,-5,-3,]),'AND':([1,2,7,8,9,10,11,],[5,-1,-2,5,-4,5,-3,]),'OR':([1,2,7,8,9,10,11,],[6,-1,-2,6,-4,-5,-3,]),'RPAREN':([2,7,8,9,10,11,],[-1,-2,11,-4,-5,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,],[1,7,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VARIABLE','expression',1,'p_expression_variable','my_ply.py',39),
  ('expression -> NOT expression','expression',2,'p_expression_not','my_ply.py',43),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','my_ply.py',47),
  ('expression -> expression AND expression','expression',3,'p_expression_and','my_ply.py',51),
  ('expression -> expression OR expression','expression',3,'p_expression_or','my_ply.py',55),
]
